//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hittafotbollsplaner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fotbollsplaner
    {
        public int Id { get; set; }
        public string Namn { get; set; }
        public string Adress { get; set; }
        public string Ort { get; set; }
        public string Postnummer { get; set; }
        public string Underlag { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string AntalGras { get; set; }
        public string AntalGrus { get; set; }
        public string AntalKonstGras { get; set; }
        public Nullable<bool> Parkering { get; set; }
        public Nullable<bool> Kafe { get; set; }
        public Nullable<bool> Omkladnadsrum { get; set; }
    }
}
