//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hittafotbollsplaner.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class fotbollsplaner
    {
        public int Id { get; set; }
        public string Namn { get; set; }
        public string Adress { get; set; }
        public string Ort { get; set; }
        public string Postnummer { get; set; }
        public string Underlag { get; set; }
    }
}
