//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hittafotbollsplaner.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class fotbollsplaner
    {
        public int Id { get; set; }
        [Required, StringLength(25, MinimumLength = 3, ErrorMessage = "Namnet bör vara minst tre bokstäver.")]
        public string Namn { get; set; }
        [Required, StringLength(25, MinimumLength =3, ErrorMessage ="Adressen bör vara minst tre bokstäver.")]
        public string Adress { get; set; }
        [Required, StringLength(20, MinimumLength = 3, ErrorMessage = "Ortsnamnet bör vara minst tre bokstäver.")]
        public string Ort { get; set; }
        [Required, StringLength(5, MinimumLength = 5, ErrorMessage = "Postnummret bör vara fem siffor ihop.")]
        public string Postnummer { get; set; }
        //[Required, StringLength(20, MinimumLength = 4, ErrorMessage = "Vänligen fyll i rätt underlag.")]
        public string Underlag { get; set; }

    }
}
